namespace SF2_Hex_Utility
{
    partial class EditFieldDetails
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.label6 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.label10 = new System.Windows.Forms.Label();
            this.label8 = new System.Windows.Forms.Label();
            this.label9 = new System.Windows.Forms.Label();
            this.label11 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.lblName = new System.Windows.Forms.Label();
            this.lblLocation = new System.Windows.Forms.Label();
            this.lblLength = new System.Windows.Forms.Label();
            this.label12 = new System.Windows.Forms.Label();
            this.lblRefType = new System.Windows.Forms.Label();
            this.lblFormat = new System.Windows.Forms.Label();
            this.lblValue = new System.Windows.Forms.Label();
            this.lblOriginalValue = new System.Windows.Forms.Label();
            this.picHex = new System.Windows.Forms.PictureBox();
            this.txtDescription = new System.Windows.Forms.TextBox();
            this.picRom = new System.Windows.Forms.PictureBox();
            this.label2 = new System.Windows.Forms.Label();
            this.lblContextAutoGenerated = new System.Windows.Forms.Label();
            this.toolTip1 = new System.Windows.Forms.ToolTip(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.picHex)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.picRom)).BeginInit();
            this.SuspendLayout();
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Location = new System.Drawing.Point(190, 35);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(48, 13);
            this.label6.TabIndex = 5;
            this.label6.Text = "Location";
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Location = new System.Drawing.Point(36, 9);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(35, 13);
            this.label3.TabIndex = 6;
            this.label3.Text = "Name";
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(380, 35);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(40, 13);
            this.label1.TabIndex = 5;
            this.label1.Text = "Length";
            // 
            // label10
            // 
            this.label10.AutoSize = true;
            this.label10.Location = new System.Drawing.Point(3, 351);
            this.label10.Name = "label10";
            this.label10.Size = new System.Drawing.Size(60, 13);
            this.label10.TabIndex = 9;
            this.label10.Text = "Description";
            // 
            // label8
            // 
            this.label8.AutoSize = true;
            this.label8.Location = new System.Drawing.Point(20, 35);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(51, 13);
            this.label8.TabIndex = 10;
            this.label8.Text = "Ref Type";
            // 
            // label9
            // 
            this.label9.AutoSize = true;
            this.label9.Location = new System.Drawing.Point(32, 58);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(39, 13);
            this.label9.TabIndex = 11;
            this.label9.Text = "Format";
            // 
            // label11
            // 
            this.label11.AutoSize = true;
            this.label11.Location = new System.Drawing.Point(11, 113);
            this.label11.Name = "label11";
            this.label11.Size = new System.Drawing.Size(43, 13);
            this.label11.TabIndex = 12;
            this.label11.Text = "Context";
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Location = new System.Drawing.Point(174, 61);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(72, 13);
            this.label4.TabIndex = 13;
            this.label4.Text = "Original Value";
            // 
            // lblName
            // 
            this.lblName.BackColor = System.Drawing.SystemColors.Control;
            this.lblName.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblName.Font = new System.Drawing.Font("Consolas", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblName.Location = new System.Drawing.Point(77, 6);
            this.lblName.Margin = new System.Windows.Forms.Padding(3);
            this.lblName.Name = "lblName";
            this.lblName.Padding = new System.Windows.Forms.Padding(3);
            this.lblName.Size = new System.Drawing.Size(400, 20);
            this.lblName.TabIndex = 14;
            this.lblName.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // lblLocation
            // 
            this.lblLocation.BackColor = System.Drawing.SystemColors.Control;
            this.lblLocation.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblLocation.Font = new System.Drawing.Font("Consolas", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblLocation.Location = new System.Drawing.Point(244, 32);
            this.lblLocation.Margin = new System.Windows.Forms.Padding(3);
            this.lblLocation.Name = "lblLocation";
            this.lblLocation.Padding = new System.Windows.Forms.Padding(3);
            this.lblLocation.Size = new System.Drawing.Size(124, 20);
            this.lblLocation.TabIndex = 14;
            this.lblLocation.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.toolTip1.SetToolTip(this.lblLocation, "Use depends upon Reference Type.\r\nAbsolute = the specific location to edit.\r\nWild" +
        "card Match = the first byte to begin the search.");
            // 
            // lblLength
            // 
            this.lblLength.BackColor = System.Drawing.SystemColors.Control;
            this.lblLength.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblLength.Font = new System.Drawing.Font("Consolas", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblLength.Location = new System.Drawing.Point(426, 32);
            this.lblLength.Margin = new System.Windows.Forms.Padding(3);
            this.lblLength.Name = "lblLength";
            this.lblLength.Padding = new System.Windows.Forms.Padding(3);
            this.lblLength.Size = new System.Drawing.Size(51, 20);
            this.lblLength.TabIndex = 14;
            this.lblLength.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.toolTip1.SetToolTip(this.lblLength, "Number of bytes to edit.");
            // 
            // label12
            // 
            this.label12.AutoSize = true;
            this.label12.Location = new System.Drawing.Point(187, 87);
            this.label12.Name = "label12";
            this.label12.Size = new System.Drawing.Size(59, 13);
            this.label12.TabIndex = 10;
            this.label12.Text = "New Value";
            // 
            // lblRefType
            // 
            this.lblRefType.BackColor = System.Drawing.SystemColors.Control;
            this.lblRefType.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblRefType.Font = new System.Drawing.Font("Consolas", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblRefType.Location = new System.Drawing.Point(77, 32);
            this.lblRefType.Margin = new System.Windows.Forms.Padding(3);
            this.lblRefType.Name = "lblRefType";
            this.lblRefType.Padding = new System.Windows.Forms.Padding(3);
            this.lblRefType.Size = new System.Drawing.Size(94, 20);
            this.lblRefType.TabIndex = 14;
            this.lblRefType.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.toolTip1.SetToolTip(this.lblRefType, "How the location to edit in the rom is determined.\r\nAbsolute = specify the locati" +
        "on exactly.\r\nWildcard Match = search for the first location in the rom matching " +
        "the provided bytes.");
            // 
            // lblFormat
            // 
            this.lblFormat.BackColor = System.Drawing.SystemColors.Control;
            this.lblFormat.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblFormat.Font = new System.Drawing.Font("Consolas", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblFormat.Location = new System.Drawing.Point(77, 58);
            this.lblFormat.Margin = new System.Windows.Forms.Padding(3);
            this.lblFormat.Name = "lblFormat";
            this.lblFormat.Padding = new System.Windows.Forms.Padding(3);
            this.lblFormat.Size = new System.Drawing.Size(94, 20);
            this.lblFormat.TabIndex = 14;
            this.lblFormat.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.toolTip1.SetToolTip(this.lblFormat, "Format of the data to edit.");
            // 
            // lblValue
            // 
            this.lblValue.BackColor = System.Drawing.SystemColors.Control;
            this.lblValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblValue.Font = new System.Drawing.Font("Consolas", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblValue.Location = new System.Drawing.Point(244, 84);
            this.lblValue.Margin = new System.Windows.Forms.Padding(3);
            this.lblValue.Name = "lblValue";
            this.lblValue.Padding = new System.Windows.Forms.Padding(3);
            this.lblValue.Size = new System.Drawing.Size(233, 20);
            this.lblValue.TabIndex = 14;
            this.lblValue.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.toolTip1.SetToolTip(this.lblValue, "The value in the currently loaded rom.");
            // 
            // lblOriginalValue
            // 
            this.lblOriginalValue.BackColor = System.Drawing.SystemColors.Control;
            this.lblOriginalValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblOriginalValue.Font = new System.Drawing.Font("Consolas", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblOriginalValue.Location = new System.Drawing.Point(244, 58);
            this.lblOriginalValue.Margin = new System.Windows.Forms.Padding(3);
            this.lblOriginalValue.Name = "lblOriginalValue";
            this.lblOriginalValue.Padding = new System.Windows.Forms.Padding(3);
            this.lblOriginalValue.Size = new System.Drawing.Size(233, 20);
            this.lblOriginalValue.TabIndex = 14;
            this.lblOriginalValue.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.toolTip1.SetToolTip(this.lblOriginalValue, "The hex value in an unaltered rom.");
            // 
            // picHex
            // 
            this.picHex.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.picHex.Location = new System.Drawing.Point(77, 113);
            this.picHex.Name = "picHex";
            this.picHex.Size = new System.Drawing.Size(400, 111);
            this.picHex.TabIndex = 15;
            this.picHex.TabStop = false;
            this.toolTip1.SetToolTip(this.picHex, "Bytes around the edit location in the rom.\r\nUse the context to ensure the correct" +
        " location is being edit.\r\nThe highlighted text is the location being edited.");
            this.picHex.Paint += new System.Windows.Forms.PaintEventHandler(this.picHex_Paint);
            // 
            // txtDescription
            // 
            this.txtDescription.Font = new System.Drawing.Font("Consolas", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtDescription.Location = new System.Drawing.Point(77, 349);
            this.txtDescription.Multiline = true;
            this.txtDescription.Name = "txtDescription";
            this.txtDescription.ReadOnly = true;
            this.txtDescription.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.txtDescription.Size = new System.Drawing.Size(400, 185);
            this.txtDescription.TabIndex = 16;
            // 
            // picRom
            // 
            this.picRom.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.picRom.Location = new System.Drawing.Point(77, 230);
            this.picRom.Name = "picRom";
            this.picRom.Size = new System.Drawing.Size(400, 111);
            this.picRom.TabIndex = 15;
            this.picRom.TabStop = false;
            this.toolTip1.SetToolTip(this.picRom, "Bytes around the edit location from the rom.\r\nThe highlighted text is the locatio" +
        "n being edited.");
            this.picRom.Paint += new System.Windows.Forms.PaintEventHandler(this.picRom_Paint);
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(11, 230);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(29, 13);
            this.label2.TabIndex = 12;
            this.label2.Text = "Rom";
            // 
            // lblContextAutoGenerated
            // 
            this.lblContextAutoGenerated.AutoSize = true;
            this.lblContextAutoGenerated.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(192)))), ((int)(((byte)(0)))));
            this.lblContextAutoGenerated.Location = new System.Drawing.Point(8, 138);
            this.lblContextAutoGenerated.Name = "lblContextAutoGenerated";
            this.lblContextAutoGenerated.Size = new System.Drawing.Size(60, 26);
            this.lblContextAutoGenerated.TabIndex = 17;
            this.lblContextAutoGenerated.Text = "(Auto \r\nGenerated)";
            this.lblContextAutoGenerated.Visible = false;
            // 
            // toolTip1
            // 
            this.toolTip1.Active = false;
            this.toolTip1.AutoPopDelay = 5000;
            this.toolTip1.InitialDelay = 100;
            this.toolTip1.IsBalloon = true;
            this.toolTip1.ReshowDelay = 100;
            // 
            // EditFieldDetails
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.lblContextAutoGenerated);
            this.Controls.Add(this.txtDescription);
            this.Controls.Add(this.picRom);
            this.Controls.Add(this.picHex);
            this.Controls.Add(this.lblFormat);
            this.Controls.Add(this.lblRefType);
            this.Controls.Add(this.lblLength);
            this.Controls.Add(this.lblOriginalValue);
            this.Controls.Add(this.lblValue);
            this.Controls.Add(this.lblLocation);
            this.Controls.Add(this.lblName);
            this.Controls.Add(this.label9);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.label11);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.label10);
            this.Controls.Add(this.label12);
            this.Controls.Add(this.label8);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.label6);
            this.Controls.Add(this.label3);
            this.Name = "EditFieldDetails";
            this.Size = new System.Drawing.Size(493, 556);
            ((System.ComponentModel.ISupportInitialize)(this.picHex)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.picRom)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label10;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.Label label9;
        private System.Windows.Forms.Label label11;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label lblName;
        private System.Windows.Forms.Label lblLocation;
        private System.Windows.Forms.Label lblLength;
        private System.Windows.Forms.Label label12;
        private System.Windows.Forms.Label lblRefType;
        private System.Windows.Forms.Label lblFormat;
        private System.Windows.Forms.Label lblValue;
        private System.Windows.Forms.Label lblOriginalValue;
        private System.Windows.Forms.PictureBox picHex;
        private System.Windows.Forms.TextBox txtDescription;
        private System.Windows.Forms.PictureBox picRom;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label lblContextAutoGenerated;
        private System.Windows.Forms.ToolTip toolTip1;
    }
}
